create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  room_code text not null,
  peer_id text not null,
  data jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists rooms_room_code_idx
  on public.rooms (room_code);

alter table public.rooms enable row level security;
